version: '3.4'
services:
  server:
    build: LinkShortener/
    ports:
      - "5129:5129"
    depends_on:
      - db
      - redis
      - rabbitmq
    container_name: server
  client:
    build: Frontend/
    ports:
      - "8080:8080"
    container_name: client
  db:
    image: postgres:15.3
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Shortener
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.13.2-management
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
  statistics_db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Shortener_Statistics
    restart: always
    ports:
      - "5434:5432"
    container_name: statistics_db