version: '3.4'
services:
  server:
    build: LinkShortener/
    ports:
      - "5129:5129"
    depends_on:
      - db
      - redis
    container_name: server
  client:
    build: Frontend/
    ports:
      - "8080:8080"
    container_name: client
  db:
    image: postgres:15.3
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Shortener
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"